[package]
name = "swap_cache"
version = "0.1.0"
authors = ["Jonathan Moore <moore@eds.org>"]
edition = "2018"

[dependencies]
hashbrown = "0.3.0"

[dev-dependencies]
criterion = "0.2"
lru = "0.1.15"
rand = "0.6.5"

[[bench]]
name = "benchmark"
harness = false